# Generated by Django 3.2.25 on 2024-09-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bomberman', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomberman',
            name='creator',
            field=models.IntegerField(default=0),
        ),
    ]
