# Generated by Django 3.2.25 on 2024-09-12 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bomberman', '0002_bomberman_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bomberman',
            name='loser_id',
        ),
        migrations.RemoveField(
            model_name='bomberman',
            name='winner_id',
        ),
    ]
