# Generated by Django 3.2.25 on 2024-09-12 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0002_pong_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pong',
            name='loser_id',
        ),
        migrations.RemoveField(
            model_name='pong',
            name='winner_id',
        ),
    ]
