# Generated by Django 3.2.25 on 2024-09-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0004_pong_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pong',
            name='loser',
            field=models.CharField(default='player2', max_length=15),
        ),
        migrations.AlterField(
            model_name='pong',
            name='winner',
            field=models.CharField(default='player1', max_length=15),
        ),
    ]
