# Generated by Django 3.2.25 on 2024-09-24 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofiles', '0002_status_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student42',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login42', models.CharField(default='', max_length=16)),
                ('picture', models.CharField(default='', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '42 Student',
                'verbose_name_plural': '42 Students',
            },
        ),
    ]
